version: '3.8'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-multi-session-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=whatsapp-api-key-2024
      # - WEBHOOK_URL=http://tu-webhook-url.com/endpoint
    volumes:
      # Persistir sesiones de WhatsApp
      - ./sessions:/usr/src/app/.wwebjs_auth
      # Persistir cache de sesiones
      - ./cache:/usr/src/app/.wwebjs_cache
    restart: unless-stopped
    shm_size: 2gb
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Opcional: Nginx como reverse proxy
  nginx:
    image: nginx:alpine
    container_name: whatsapp-api-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl:/etc/nginx/ssl  # Para HTTPS
    depends_on:
      - whatsapp-api
    restart: unless-stopped
    profiles:
      - nginx  # Para usar: docker compose --profile nginx up -d

volumes:
  sessions:
    driver: local
  cache:
    driver: local